//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Base_de_datos
{
    using System;
    using System.Collections.Generic;
    
    public partial class Articles : Belongings
    {
        public int idArticle { get; set; }
        public string barCode { get; set; }
        public Nullable<double> price { get; set; }
        public string state { get; set; }
    
        public virtual Sales Sale { get; set; }
        public virtual SetAside SetAside { get; set; }
    }
}
