//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Base_de_datos
{
    using System;
    using System.Collections.Generic;
    
    public partial class Articles : Belongings
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Articles()
        {
            this.ArticlesSetAside = new HashSet<ArticlesSetAside>();
        }
    
        public int idArticle { get; set; }
        public string barCode { get; set; }
        public Nullable<double> sellingPrice { get; set; }
        public string state { get; set; }
        public string customerProfit { get; set; }
        public string storeProfit { get; set; }
        public System.DateTime creationDate { get; set; }
    
        public virtual Sales Sale { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ArticlesSetAside> ArticlesSetAside { get; set; }
    }
}
