//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Base_de_datos
{
    using System;
    using System.Collections.Generic;
    
    public partial class Belongings
    {
        public int idBelonging { get; set; }
        public double amountAppraised { get; set; }
        public string category { get; set; }
        public string description { get; set; }
        public string images { get; set; }
        public string characteristics { get; set; }
        public string loanAmount { get; set; }
    
        public virtual Contracts Contract { get; set; }
    }
}
