//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Base_de_datos
{
    using System;
    using System.Collections.Generic;
    
    public partial class Contracts
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Contracts()
        {
            this.Belongings = new HashSet<Belongings>();
        }
    
        public int idContract { get; set; }
        public double amountLoaned { get; set; }
        public Nullable<int> idContractPrevious { get; set; }
        public System.DateTime deadlineDate { get; set; }
        public System.DateTime creationDate { get; set; }
        public string state { get; set; }
        public int iva { get; set; }
        public Nullable<int> interestRate { get; set; }
    
        public virtual Staff Staff { get; set; }
        public virtual Customers Customer { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Belongings> Belongings { get; set; }
    }
}
