//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Base_de_datos
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class Connection : DbContext
    {
        public Connection()
            : base("name=Connection")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<SetAside> SetAsides { get; set; }
        public virtual DbSet<Belongings> Belongings { get; set; }
        public virtual DbSet<Customers> Customers { get; set; }
        public virtual DbSet<Contracts> Contracts { get; set; }
        public virtual DbSet<Staff> Staffs { get; set; }
        public virtual DbSet<Sales> Sales { get; set; }
        public virtual DbSet<Operations> Operations { get; set; }
    }
}
