//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Base_de_datos
{
    using System;
    using System.Collections.Generic;
    
    public partial class ImagesBelonging
    {
        public int idImagenBelonging { get; set; }
        public byte[] imagen { get; set; }
    
        public virtual Belongings Belonging { get; set; }
    }
}
