//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Base_de_datos
{
    using System;
    using System.Collections.Generic;
    
    public partial class Operations
    {
        public int idOperation { get; set; }
        public string concept { get; set; }
        public System.DateTime operationDate { get; set; }
        public double amount { get; set; }
    
        public virtual Staff Staff { get; set; }
    }
}
